const portfolio = [
['01-a-little-princess.jpg','A Little Princess'],['02-a-study-in-scarlot-the-sign-of-four-sherlock-holmes.jpg','Sherlock Holmes Collection'],['03-as-a-man-thinketh.jpg','As A Man Thinketh'],['04-beyond-good-and-evil.jpg','Beyond Good and Evil'],['05-emma.jpg','Emma'],['06-how-to-win-frinds-influence-people.jpg','How to Win Friends'],['07-mansfield-park.jpg','Mansfield Park'],['08-peter-pan.jpg','Peter Pan'],['09-pride-prejudice.jpg','Pride & Prejudice'],['10-persuasion.jpg','Persuasion'],['11-sense-sensibility.jpg','Sense & Sensibility'],['12-sherlock-holmes-his-last-bow.jpg','His Last Bow'],['13-the-adventures-of-sherlock-holmes.jpg','Adventures of Sherlock Holmes'],['14-the-case-book-of-sherlock-holmes.jpg','Case Book of Sherlock Holmes'],['15-the-hound-of-the-baskervillcs-sherlock-holmes.jpg','Hound of the Baskervilles'],['16-the-memoirs-of-sherlock-holmes.jpg','Memoirs of Sherlock Holmes'],['17-the-picture-of-dorian-gray.jpg','The Picture of Dorian Gray'],['18-the-power-of-your-subconscious-mind.jpg','Power of Your Subconscious Mind'],['19-the-return-of-sherlock-holmes.jpg','Return of Sherlock Holmes'],['20-the-richest-man-in-babylon.jpg','Richest Man in Babylon'],['21-the-wizard-of-oz.jpg','The Wizard of Oz'],['22-think-and-grow-rich.jpg','Think and Grow Rich'],['23-tao-te-ching.jpg','Tao Te Ching'],['24-the-great-gatsby.jpg','The Great Gatsby'],['25-the-little-prince.jpg','The Little Prince'],['26-the-prophet.jpg','The Prophet'],['27-the-secret-garden.jpg','The Secret Garden'],['28-wuthering-heights.jpg','Wuthering Heights']
];
const grid=document.getElementById('portfolioGrid');
portfolio.forEach(([file,title])=>{const card=document.createElement('article');card.className='portfolio-card reveal';card.innerHTML=`<img loading="lazy" src="images/portfolio/${file}" alt="${title}"><div>${title}</div>`;card.onclick=()=>openLightbox(file,title);grid.appendChild(card)});
function openLightbox(file,title){document.getElementById('lightboxImg').src=`images/portfolio/${file}`;document.getElementById('lightboxTitle').textContent=title;document.getElementById('lightbox').classList.add('active')}
document.getElementById('closeLightbox').onclick=()=>document.getElementById('lightbox').classList.remove('active');
document.getElementById('lightbox').onclick=e=>{if(e.target.id==='lightbox')e.currentTarget.classList.remove('active')};
document.getElementById('year').textContent=new Date().getFullYear();
document.getElementById('menuBtn').onclick=()=>document.getElementById('nav').classList.toggle('open');
const reveal=()=>document.querySelectorAll('.reveal').forEach(el=>{if(el.getBoundingClientRect().top<innerHeight-80)el.classList.add('visible')});addEventListener('scroll',reveal);reveal();
addEventListener('mousemove',e=>{document.documentElement.style.setProperty('--x',e.clientX+'px');document.documentElement.style.setProperty('--y',e.clientY+'px')});
